import Head from 'next/head';
import SiteHeader from '@/components/siteheader';
import SiteNav from '@/components/sitenav';
import SiteFooter from '@/components/sitefooter';

export default function DefaultLayout({ children }) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SiteHeader />
      <SiteNav />
      <>{children}</>
      <SiteFooter />
    </>
  );
}
