import Head from 'next/head';
import SiteHeader from '@/components/siteheader';
import SiteNav from '@/components/sitenav';
import SiteFooter from '@/components/sitefooter';

export default function DefaultLayout({ children }) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Barlow:ital,wght@0,100;0,400;0,700;0,900;1,100;1,400;1,700;1,900&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined"
          rel="stylesheet"
        />
        <link rel="icon" href="/favicon.ico" />

        <link href="./styles/globals.css" rel="stylesheet" />
      </Head>
      <div className="layout_m">
        <div className="layout_m-header">
          <SiteHeader />
        </div>
        <div className="layout_m-nav">
          <SiteNav />
        </div>
        <div className="layout_m-main">
          <>{children}</>
        </div>
        <div className="layout_m-footer">
          <SiteFooter />
        </div>
      </div>
    </>
  );
}
