import Head from 'next/head';
import SiteHeader from '@/components/siteheader';
import SiteFooter from '@/components/sitefooter';

export default function StrippedLayout({ children }) {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <SiteHeader />
      <>{children}</>
      <SiteFooter />
    </>
  );
}
